### ISSUE TITLE
Unable to perform any action on spotify

### ISSUE THREAD

**Issue by vipykae** [dorianturgot/AlbumSortify#9]
It seems like the connection with Spotify is broken.
The fecthing of the albums works fine, but the website is unable to fetch the current list or to create one.
It is most probably CORS related.

![image](https://github.com/dorianturgot/AlbumSortify/assets/9498111/5406d4a9-3545-4547-b609-1aec79f61082)

**Comment by vipykae** [comment]
Anyway, this app is probably a bit obsolete now that you can drag and drop an album into a folder to do the same.

**Comment by dorianturgot** [comment]
Hi, the problem should be fixed now !
I don't really like Spotify's solution because it mixes folders with your playlists and saved playlists. That's why I went for a simpler approach that just shows albums. That's why I've added a "New Releases" section so you can easily check out the latest albums.

I made this website so you can create and share album playlists easily, whether it's for yourself or with friends. Hope you enjoy it !

**Comment by vipykae** [comment]
Thanks for your responsiveness !
Nos francais ont du talent, keep it up ! 😎
